# Header
menu:
  Home: /
rss: ../feed

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics: UA-66625644-1
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
